stages:
  - sync

.base:
  before_script:
    - set -euo pipefail
  tags:
    - d13-runner

sync-repository:
  extends: .base
  stage: sync
  only:
    - feature/sync-repo
  
  script:
    - |
      #!/bin/bash
      
      pwd
    
