image: shivammathur/node:latest

stages:
  - check
  - release

.base:
  before_script:
    - set -euo pipefail
  tags:
    - d13-runner
tests:
  stage: check
  extends: .base
  only:
    - feature/ci-test
  
  script:
    # Update spc (See https://github.com/shivammathur/spc for options)
    - spc -U
  
    # Setup PHP
    - spc --php-version "$PHP_VERSION" --extensions "bcmath, ctype, curl, dom, fileinfo, filter,gd, hash, iconv, intl, json, libxml, mbstring, openssl, pcre, pdo_mysql, simplexml, soap, sockets, sodium, xsl, tokenizer, xmlwriter, xsl, zlib, libxml"

    - composer config --global gitlab-token.git.nfq.asia $GITLAB_ACCESS_TOKEN
    - composer install --prefer-dist --no-progress --no-interaction
  
    # Run coding standard
    - ./vendor/bin/ecs --no-progress-bar
    - vendor/bin/rector process --dry-run
    
    - npm install

build-archive:
  extends: .base
  stage: release
  only:
    - master
  before_script:
    - apt-get update
    - apt-get install -qq zip # installs zip utility in Alpine Linux
    - export npm_config_loglevel=silent
  script:
    - |
      #!/bin/bash
      
      spc -U
      
      # Setup PHP
      spc --php-version 8.1 --extensions "mbstring, curl, dom, fileinfo, gd, iconv, intl, json, xml, mbstring, pdo, phar, zip, sodium, pdo_mysql, bcmath, soap";
      
      npm install --quiet 2>&1 ;
      
      rm -rf dist/ ;
      
      echo "Starting build..."
      
      if npm run build > /dev/null 2>&1; then
         echo "Build completed successfully"
      else
         echo "Build failed"
         exit 1
      fi
      
      composer install --no-dev --optimize-autoloader;
      
      # Set up a temporary directory
      TEMP_DIR="/tmp/$CI_COMMIT_SHA"
      
      # Create the temporary directory
      mkdir -p "$TEMP_DIR"
      
      cp twint-woocommerce-extension.php "$TEMP_DIR"
      cp -r dist "$TEMP_DIR"
      cp -r src "$TEMP_DIR"
      cp -r assets "$TEMP_DIR"
      cp -r bin "$TEMP_DIR"
      cp -r vendor "$TEMP_DIR"
      
      cd "$TEMP_DIR"
      zip -r twint-woocommerce-extension.zip .  > /dev/null 2>&1;
      
      cd -
      mv "$TEMP_DIR/twint-woocommerce-extension.zip" .
  artifacts:
    paths:
      - "twint-woocommerce-extension.zip"
    expire_in: 1 week


release:
  only:
    - tags
  stage: release
  image: alpine:3
  extends: .base
  variables:
    GIT_DEPTH: 0
  script:
    - apk add --no-cache git openssh bash
    - ./bin/sync.sh
