image: shivammathur/node:latest

variables:
  COMPOSER_ALLOW_SUPERUSER: "1"

stages:
  - check
  - release

.base:
  before_script:
    - set -euo pipefail
  tags:
    - d13-runner
tests:
  stage: check
  extends: .base
  only:
    - branches
    - tags
  parallel:
    matrix:
      - PHP_VERSION: [ "8.1", "8.2", "8.3" ]
  
  script:
    # Update spc (See https://github.com/shivammathur/spc for options)
    - spc -U
  
    # Setup PHP
    - spc --php-version "$PHP_VERSION" --extensions "bcmath, ctype, curl, dom, fileinfo, filter,gd, hash, iconv, intl, json, libxml, mbstring, openssl, pcre, pdo_mysql, simplexml, soap, sockets, sodium, xsl, tokenizer, xmlwriter, xsl, zlib, libxml"

    - composer config --global gitlab-token.git.nfq.asia $GITLAB_ACCESS_TOKEN
    - composer install --prefer-dist --no-progress --no-interaction
  
    # Run coding standard
    - ./vendor/bin/ecs --no-progress-bar
    - vendor/bin/rector process --dry-run
    - vendor/bin/phpstan analyse --memory-limit=1024M
    
    - npm install
    - npx prettier --check ./resources/

build-archive:
  extends: .base
  stage: release
  only:
    - branches
    - tags
  parallel:
    matrix:
      - PHP_VERSION: [ "8.1"]
  before_script:
    - apt-get update
    - apt-get install -qq jq zip # installs zip utility in Alpine Linux
    - export npm_config_loglevel=silent
  script:
    - |
      #!/bin/bash
      
      spc -U
      
      # Setup PHP
      spc --php-version "$PHP_VERSION" --extensions "mbstring, curl, dom, fileinfo, gd, iconv, intl, json, xml, mbstring, pdo, phar, zip, sodium, pdo_mysql, bcmath, soap";
      composer config --global gitlab-token.git.nfq.asia $GITLAB_ACCESS_TOKEN
      rootdir=$(pwd)
  
      npm install --quiet 2>&1 ;
  
      # Rebuild dist files
      rm -rf dist/
      npm run build > /dev/null 2>&1
      
      composer global require humbug/php-scoper
      composer install --no-dev --optimize-autoloader;
      rm -rf infra
      php -d memory_limit=-1 /root/.composer/vendor/bin/php-scoper add-prefix --working-dir ./ --config scoper.inc.php --output-dir ./build
  
      PLUGIN_VERSION=$(jq -r '.version' composer.json)
      sed -i "s/@version@/$PLUGIN_VERSION/g" build/src/Woo/Constant/TwintConstant.php
      sed -i "s/InstallSource::DIRECT/InstallSource::STORE/g" src/Woo/Constant/TwintConstant.php
    
    - FILE_NAME="twint-woocommerce-extension-$(echo $CI_COMMIT_REF_NAME | sed 's/\//-/g').zip"
  
    - zip -r "./$FILE_NAME" ./build/* -x "build/" > /dev/null 2>&1;
  artifacts:
    paths:
      - "$FILE_NAME"
    expire_in: 1 week


release:
  only:
    - tags
  stage: release
  image: alpine:3
  extends: .base
  variables:
    GIT_DEPTH: 0
  script:
    - apk add --no-cache git openssh bash
    - ./bin/sync.sh
