image: shivammathur/node:latest

stages:
  - release

.base:
  before_script:
    - set -euo pipefail
  tags:
    - d13-runner

build-archive:
  extends: .base
  stage: release
  only:
    - feature/sync-repo
  before_script:
    - apt-get update
    - apt-get install -qq zip # installs zip utility in Alpine Linux
    - export npm_config_loglevel=silent
  script:
    - |
      #!/bin/bash
      
      spc -U
      
      # Setup PHP
      spc --php-version 8.1 --extensions "mbstring, curl, dom, fileinfo, gd, iconv, intl, json, xml, mbstring, pdo, phar, zip, sodium, pdo_mysql, bcmath, soap";
      
      npm install --quiet 2>&1 ;
      echo "Starting build..."
      if npm run build > /dev/null 2>&1; then
         echo "Build completed successfully"
      else
         echo "Build failed"
         exit 1
      fi
      
      rm -rf infra/ resources/ docs/ auth.json;
      
      zip -r twint.zip ./  > /dev/null 2>&1;
  
  artifacts:
    paths:
      - twint.zip
