image: shivammathur/node:latest

stages:
  - sync

.base:
  before_script:
    - set -euo pipefail
  tags:
    - d13-runner

sync-repository:
  extends: .base
  stage: sync
  only:
    - feature/sync-repo
  before_script:
    - apt-get update
    - apt-get install -qq zip # installs zip utility in Alpine Linux
  script:
    - |
      #!/bin/bash
  
      spc -U
  
      # Setup PHP
      spc --php-version 8.1 --extensions "mbstring, curl, dom, fileinfo, gd, iconv, intl, json, xml, mbstring, pdo, phar, zip, sodium, pdo_mysql, bcmath, soap";
  
      composer install --no-dev --optimize-autoloader;
      
      npm install > /dev/null 2>&1
      npm run build;
      
      rm -rf infra/ resources/ docs/ auth.json;
  
      zip -r twint.zip ./
    
  artifacts:
    paths:
      - twint.zip
