CREATE DATABASE IF NOT EXISTS `wc1` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `wc2` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `wc3` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON `wc1`.* TO 'wordpress'@'%';
GRANT ALL PRIVILEGES ON `wc2`.* TO 'wordpress'@'%';
GRANT ALL PRIVILEGES ON `wc3`.* TO 'wordpress'@'%';
FLUSH PRIVILEGES;
